# If this were an application that would be deployed in production, I would definitely have separate configs for dev, test, stage, and prod
server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /depot
spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: none